### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by hamada147**
- Overall code enhancements.
- Crated Java Version that is compatible with 1.8 (aka Java 8).
- Created Kotlin (JVM) Version.
- Implemented Unit Testing for Kotlin.
- Implemented Unit Testing for Java.

### CODE REVIEW

**Comment by osamabmaq** [comment]
Hi Hamada,
What wrong results that the code results in ? according to [this commit](https://github.com/osamabmaq/TafqeetJ/pull/1/commits/99d2e4d10ecccbeb0c0d41f6b2dac763b2fc3c55) of yours, you included some tests, and these tests expected the code to output an output for negative numbers for a positive input, Like (مئتين) for +200, whereas (مئتين) is for -200, like we say (سالب مئتين) for negative 200 and we say (مئتان) for positive 200. And that goes also for some tests you committed. If that is the case then there is nothing wrong. If there is anything else please feel free to tell me about it.

**Comment by hamada147** [comment]
Hello Osama,
The error was in my Kotlin code during the migration from Java to Kotlin. The message was meant for me.

In regards to the hundreds translations for 200. You are correct. I misplaced it.

**Comment by abd3lraouf** [comment]
didn't see this before my #2. Seems great work then

**Comment by hamada147** [comment]
Hello @AbdElraoufSabri,
Thank you 😊 . Much appreciated.

Would love your help in making it available through maven. I never did it before and all the available options I was able to find were paid ones. If there is any free one or any kind of tutorial that shows a way would be very much appreciated 🤗

**Comment by abd3lraouf** [comment]
> Hello @AbdElraoufSabri,
> Thank you  . Much appreciated.
> 
> Would love your help in making it available through Maven. I never did it before and all the available options I was able to find were paid ones. If there is any free one or any kind of tutorial that shows a way would be very much appreciated

I'm afraid it's very complex. But here are the links:
1. [Medium](https://entzik.medium.com/how-to-publish-open-source-java-libraries-to-maven-central-70f9232462f5)
2. [Proandroiddev](https://proandroiddev.com/publishing-a-maven-artifact-3-3-step-by-step-instructions-to-mavencentral-publishing-bd661081645d)
3. [Jitpack](https://www.journaldev.com/19364/jitpack-publish-android-library)

You can see here [My Library](https://github.com/AbdElraoufSabri/DatastoreWithRxJava3) published at maven under my domain, Obviously, you'd need a domain If you wanna achieve this.

**Comment by hamada147** [comment]
Thanks a lot
I will tackle them next week ISA.

**Pull request closed without merging**
